import type { Product } from './types';

// ── Productos mock compartidos entre la tienda y el admin ──────────────────
// Categorías reales de la app: alfajores, chocolates, packs, medialunas, otros
export const INITIAL_PRODUCTS: Product[] = [
    {
        id: "p1",
        name: "Alfajor Doble Chocolate",
        description: "Alfajor artesanal cubierto de chocolate negro con relleno de dulce de leche.",
        price: 2800,
        category: "Alfajores",
        image: "https://placehold.co/800x600/fce4ec/e68d8d?text=Alfajor+Chocolate",
        stock: 24,
        available: true,
        onSale: false,
        isFeatured: true,
        isNew: false,
    },
    {
        id: "p2",
        name: "Alfajor de Maicena",
        description: "Clásico alfajor de maicena con dulce de leche y coco rallado.",
        price: 2200,
        category: "Alfajores",
        image: "https://placehold.co/800x600/fff3e0/8d6e63?text=Alfajor+Maicena",
        stock: 18,
        available: true,
        onSale: false,
        isFeatured: false,
        isNew: true,
    },
    {
        id: "p3",
        name: "Tableta Chocolate Blanco",
        description: "Tableta de chocolate blanco artesanal con almendras tostadas.",
        price: 4500,
        originalPrice: 5500,
        category: "Chocolates",
        image: "https://placehold.co/800x600/f3e5f5/e68d8d?text=Chocolate+Blanco",
        stock: 8,
        available: true,
        onSale: true,
        salePercentage: 18,
        isFeatured: true,
        isNew: false,
    },
    {
        id: "p4",
        name: "Pack Difusión x6 Alfajores",
        description: "Pack ideal para regalar: 6 alfajores surtidos envueltos individualmente.",
        price: 14500,
        category: "Packs",
        image: "https://placehold.co/800x600/e8f5e9/8d6e63?text=Pack+x6",
        stock: 5,
        available: true,
        onSale: false,
        isFeatured: true,
        isNew: false,
    },
    {
        id: "p5",
        name: "Medialunas de Manteca x6",
        description: "Medialunas caseras de manteca, hojaldradas y glaseadas. 6 unidades.",
        price: 3200,
        category: "Medialunas",
        image: "https://placehold.co/800x600/fffde7/ffd180?text=Medialunas",
        stock: 0,
        available: false,
        onSale: false,
        isFeatured: false,
        isNew: false,
    },
    {
        id: "p6",
        name: "Trufas de Chocolate x8",
        description: "Trufas de chocolate belga con opciones de cacao, coco y pistachos.",
        price: 5800,
        category: "Chocolates",
        image: "https://placehold.co/800x600/fce4ec/4e342e?text=Trufas",
        stock: 12,
        available: true,
        onSale: false,
        isFeatured: false,
        isNew: true,
    },
    {
        id: "p7",
        name: "Pack Regalo Premium",
        description: "Caja premium con selección de alfajores, chocolates y trufas artesanales.",
        price: 22000,
        category: "Packs",
        image: "https://placehold.co/800x600/e3f2fd/e68d8d?text=Pack+Premium",
        stock: 3,
        available: true,
        onSale: false,
        isFeatured: true,
        isNew: false,
    },
    {
        id: "p8",
        name: "Brownie Húmedo Chocolate",
        description: "Brownie húmedo de chocolate amargo con nueces. Porción individual.",
        price: 3500,
        category: "Otros",
        image: "https://placehold.co/800x600/efebe9/8d6e63?text=Brownie",
        stock: 15,
        available: true,
        onSale: false,
        isFeatured: false,
        isNew: false,
    },
];

// Pedidos mock para el admin
export const MOCK_ORDERS = [
    {
        id: "ord-001",
        customerName: "María Rodríguez",
        phone: "+56 9 8765 4321",
        items: [{ name: "Alfajor Doble Chocolate", qty: 3, price: 2800 }, { name: "Pack x6", qty: 1, price: 14500 }],
        total: 22900,
        status: "pending_approval" as const,
        createdAt: new Date(Date.now() - 10 * 60 * 1000),
        notes: "Para regalo, envolver bonito por favor",
    },
    {
        id: "ord-002",
        customerName: "Carlos Fuentes",
        phone: "+56 9 1234 5678",
        items: [{ name: "Trufas de Chocolate x8", qty: 2, price: 5800 }],
        total: 11600,
        status: "preparing" as const,
        createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
        notes: "",
    },
    {
        id: "ord-003",
        customerName: "Ana Martínez",
        phone: "+56 9 5555 1234",
        items: [{ name: "Pack Regalo Premium", qty: 1, price: 22000 }],
        total: 22000,
        status: "shipped" as const,
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        notes: "",
    },
    {
        id: "ord-004",
        customerName: "Pedro Soto",
        phone: "+56 9 9876 5432",
        items: [{ name: "Medialunas de Manteca x6", qty: 2, price: 3200 }, { name: "Brownie", qty: 1, price: 3500 }],
        total: 9900,
        status: "delivered" as const,
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        notes: "",
    },
    {
        id: "ord-005",
        customerName: "Valentina López",
        phone: "+56 9 1111 2222",
        items: [{ name: "Tableta Chocolate Blanco", qty: 3, price: 4500 }],
        total: 13500,
        status: "pending_approval" as const,
        createdAt: new Date(Date.now() - 5 * 60 * 1000),
        notes: "Sin gluten si es posible",
    },
];
